name: actions-s3-cache
author: shonansurvivors
description: This action installs dependencies or builds, and caches them in S3.
inputs:
  s3-bucket:
    required: true
  cache-key:
    required: true
  paths:
    required: true
  zip-option:
    required: false
    default: -ryq
  unzip-option:
    required: false
    default: -nqq
  working-directory:
    required: false
    default: ./
runs:
  using: node12
  main: dist/restore/index.js
  post: dist/save/index.js
  post-if: always()
branding:
  icon: package
  color: yellow
